---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                include:
                    - ubuntu-version: 18.04
                      python-version: 3.6
                    - ubuntu-version: 20.04
                      python-version: 3.8
                    - ubuntu-version: 22.04
                      python-version: 3.10

        runs-on: ubuntu-${{ matrix.ubuntu-version }}

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  sudo apt-get install -y --no-install-recommends libtag1-dev libboost-python-dev
                  pip install -e .
            - name: Test with pytest
              run: pytest -vvv --cov=tagpy --cov-report=term-missing --cov-report=lcov
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: coverage.lcov

    integration:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                os: [fedora-35, ubuntu-18.04, ubuntu-20.04]
        name: Build ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@master

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ matrix.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ matrix.os }}-buildx

            - name: Build ${{ matrix.os }}
              uses: docker/build-push-action@v2
              with:
                  context: .
                  builder: ${{ steps.buildx.outputs.name }}
                  file: .github/Dockerfile.${{ matrix.os }}
                  push: false
                  tags: ${{ steps.prep.outputs.tagged_image }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
