---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python-version: [3.8] # because libboost-python1.74-dev only supports 3.8!
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Pip cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Pre-commit cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pre-commit
                  key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pre-commit-
            - run: sudo apt-get install -y libtag1-dev libboost-python-dev
            - run: pip install wheel
            - run: python setup.py bdist_wheel
            - run: pip install dist/*
            - run: pip install pytest pre-commit==2.17.0
            - run: pre-commit run -a
            - run: pytest -vvv -s
